method: "lr"  # Literal["mms", "lat", "lr", "mlp", "cmms"]
model_name: "llama-70b-3.3"
train_data: "repe_honesty__plain"
eval_data:
  - "roleplaying__plain"
  - "roleplaying_distribution_shift__plain"
  - "roleplaying_distribution_shift__subset"
  - "roleplaying_distribution_shift__french"
  - "roleplaying_distribution_shift__greek"
eval_on_policy: false
control_data:
  - "alpaca__plain"
id: "roleplaying_distribution_shift"
detect_only_start_of_turn: false
val_fraction: 0.2
control_on_policy: true
control_dataset_size: 10000
detect_layers: [22]
reg_coeff: 10
